### ISSUE TITLE
Interactive demo links not working anymore

### ISSUE THREAD

**Issue by manonamora** [MalifaciousGames/Mali-s-Macros#13]
Some of the .md files (like https://github.com/MalifaciousGames/Mali-s-Macros/tree/main/drag-drop-macro)  have this line:
> Interactive demo on my [website](https://malifaciousgames.neocities.org/#drag-drop-macro)

But the link doesn't send to the interactive demo :/

**Comment by MalifaciousGames** [comment]
Fair, both the drag and drop macros and the demo page need to be re-done, for know the issue is solved by deletion.
b053bf3eed739dbe9d18de40d5bcc57de18d53d2
