### ISSUE TITLE
CheckVars 2.0 is not working

### ISSUE THREAD

**Issue by CaptainWabbit** [MalifaciousGames/Mali-s-Macros#3]
I've been using the first check vars, and decided to download the new one. But when I try the new one, the 2.0. The usual <<checkvars>> macro, it doesn't do anything. So, I went back to the old one. But yeah, not sure what happen. Did you change how it works?

**Comment by MalifaciousGames** [comment]
Sorry for the late reply.

And yes, the syntax changed, the macro now creates its own button, meaning you don't have to wrap it in a `<<button/link>>`, you can use `<<checkvars>>` naked.

**Comment by CaptainWabbit** [comment]
Oh, yeah I didn't know that. That works. Thank you Mali!

**Comment by CaptainWabbit** [comment]
Oh, yeah I didn't know that. That works. Thank you Mali!
