### ISSUE TITLE
Tooltip on hover-macro is overflowing

### ISSUE THREAD

**Issue by CaptainWabbit** [MalifaciousGames/Mali-s-Macros#4]
Basically, when I hovered over, if the element is near the edge of the viewport, it will overflow and cut parts of the tooltip. I modify some of the css to make it works, like setting the width: maxcontent to something else. But atm, it's not the ideal solution. Is there a better solution to this?

**Comment by MalifaciousGames** [comment]
The tooltip part of the `<<hover>>` macro contains a lot of oversights, I didn't test it thoroughly enough before release. I plan to redo it properly when things settle a bit on my end.

I would suggest using Hiev's `<<hovertip>>`... except Hiev's sample code website is currently unavailable.

This might be the [next best thing](https://www.reddit.com/r/twinegames/comments/12kt17s/comment/jg5qpwd/?utm_source=share&utm_medium=web2x&context=3) but I haven't tried this `<<tip>>` macro.

**Comment by CaptainWabbit** [comment]
I will check the alternative. Thank you Mali. Will wait for your next version of the hover macro

**Comment by MalifaciousGames** [comment]
This has hopefully been fixed with `<<hover>>`'s latest version, complete with super strong overflow security!
It's just missing a `readme` on Github...

**Comment by CaptainWabbit** [comment]
Thank you Mali. I will use it :)
